### ISSUE TITLE
Turning this into a bot

### ISSUE THREAD

**Issue by foolip** [saschanaz/webidl-updater#1]
It looks like there's code in this repo to automatically edit specs.

The missing pieces to automatically sending PRs would be to find all specs, and to send the PRs. I think the pieces for that fairly achievable.

First, to find all specs, there are at least two approaches:
- from a manually maintained spec list, like https://github.com/tidoust/reffy
- by crawling GitHub for spec source, like https://github.com/foolip/bikeshed-tests

Then, one needs to create pull requests. I have a few projects that do that:
- https://github.com/foolip/bikeshed-tests (Python)
- https://github.com/foolip/safari-technology-preview-updater (Node)
- https://github.com/tidoust/reffy-reports/tree/master/wpt-sync (also Node)

**Comment by saschanaz** [comment]
Thank you! Those examples look helpful, I will try getting some time to implement that piece.

(This tool already depends on a forked version of reffy, the first one is achieved 🎉)

**Comment by dontcallmedom** [comment]
@saschanaz what an amazing piece of work, thank you so much!

**Comment by saschanaz** [comment]
Thank you for your appreciation! ♥♥
