### ISSUE TITLE
Automated pull request against WebXR has a bad diff

### ISSUE THREAD

**Issue by toji** [saschanaz/webidl-updater#12]
In https://github.com/immersive-web/webxr/pull/1116 the diff is extremely large and seems to be against a fairly old version of the spec, which means that many of the listed differences already exist in tip-of-tree. Not sure what happened there, but it makes it difficult to see the relevant changes and made it so that the PR is listed as conflicting.

On the positive side showing the validation messages from webidl2.js in the comment does help me pinpoint the changes that it's attempting to make and allows me to manually do the same thing relatively trivially, so kudos for that!

If there's anything that the WebXR spec is doing that prevents tools like this from functioning properly we'd love to hear about it!

**Comment by saschanaz** [comment]
Fixed it and opened https://github.com/immersive-web/webxr/pull/1118, thanks for reporting this!

It was a bug that the branch incorrectly did not get the latest commits and only get the latest file content.
