### ISSUE TITLE
Add source repo for wot-scripting

### ISSUE THREAD

**Issue by zolkis** [saschanaz/webidl-updater#13]
I am not sure what is the recommended way to extend the `spec-sources.json` - is it possible to include a new repo (already has a PR for the `void` --> `undefined` fix, but subscribing for future updates).

``` javascript
  "https://w3c.github.io/wot-scripting-api/": {
    "shortName": "wot-scripting",
    "url": "https://w3c.github.io/wot-scripting-api/",
    "source": "https://github.com/w3c/wot-scripting-api/blob/master/index.html",
    "github": {
      "owner": "w3c",
      "repo": "wot-scripting-api",
      "branch": "master",
      "path": "index.html"
    }
  },
```

**Comment by saschanaz** [comment]
It's generated from [browser-specs](https://github.com/w3c/browser-specs/blob/master/index.json), which AFAIK again depends on W3C APIs. cc @tidoust

**Comment by zolkis** [comment]
I understand. It's not really a browser spec.
If adding a second list is troublesome, then just close this, as I will get notified for changes by web-nfc anyway, and then could update wot-scripting manually.

**Comment by saschanaz** [comment]
@zolkis But it does consider a browser implementation based on the rationale page, right? In that case I guess browser-specs should include it, or otherwise I can add a manual list here.

**Comment by zolkis** [comment]
It's not a native implementation. It can run in the browser as a library:
https://github.com/eclipse/thingweb.node-wot 
Proper browser implementations would have to add too many dependencies and I don't see that happening any time soon.

**Comment by saschanaz** [comment]
Fixed by 72f798c3bcb9f772706ea3d1a7646b806629dc55 👍

**Comment by zolkis** [comment]
Wow, thank you!

**Comment by tidoust** [comment]
FWIW, we're trying to apply [selection criteria](https://github.com/w3c/browser-specs/#spec-selection-criteria) to assess whether a spec should be added to browser-specs. One of the criteria is whether "web browsers expressed some level of support for the spec, e.g. through a public intent to implement". We're not aware of such intents for the WoT Scripting API, and did not include the spec as a result.

This criterion also explains why we only add new proposals after some time, once they are more than "just an idea".
