### ISSUE TITLE
Promise<void> => Promise<undefined> automated PR left several instances unchanged

### ISSUE THREAD

**Issue by joeyparrish** [saschanaz/webidl-updater#14]
After https://github.com/w3c/encrypted-media/pull/474 updated `Promise<void>` to `Promise<undefined>`, several instances were left unchanged, leading to an error in respec:

> Couldn't match "void" to anything in the document or in any other document cited in this specification: html, webidl.

These were updated manually in https://github.com/w3c/encrypted-media/commit/1f420568ed5b5287d71e2308f4ac5be885a5ac24

I'm not familiar enough with this tool to know if this additional manual fixup is expected or not.

**Comment by saschanaz** [comment]
Yes, any non-IDL descriptions should still be updated manually, as this tool unfortunately only understand IDL syntax without knowledge about bikeshed or ReSpec. I don't think it's something that can be done by this tool, and such renaming should probably be rare enough.

Thanks for reporting though!

**Comment by joeyparrish** [comment]
Understood.  Thanks!
