### ISSUE TITLE
Change in scroll-animations location

### ISSUE THREAD

**Issue by stephenmcgruer** [saschanaz/webidl-updater#4]
Hey; I'm coming here from https://github.com/WICG/scroll-animations/pull/54

scroll-animations just recently moved to csswg-drafts: https://github.com/w3c/csswg-drafts/tree/master/scroll-animations-1

Is there any step we need to take to notify the `webidl-updater` bot about that, or will it just pick up the new repo location from some source soon?

Thanks!

**Comment by saschanaz** [comment]
Pending change on reffy side: https://github.com/tidoust/reffy/pull/179

Thanks for opening this issue!

**Comment by saschanaz** [comment]
Closed by 72d0d03a51a4933775ba76ca36055627d27365ee

**Comment by stephenmcgruer** [comment]
Thanks so much for the quick turnaround!
