### ISSUE TITLE
<dfn>s stripped from Fullscreen's IDL

### ISSUE THREAD

**Issue by foolip** [saschanaz/webidl-updater#5]
See https://github.com/whatwg/fullscreen/pull/157/files

**Comment by saschanaz** [comment]
What does the `<dfn>`s do there? Will the IDL types ignored when those `<dfn>`s are removed?

**Comment by foolip** [comment]
I don't know if they do anything, but preserving markup seems important because there must be some markup that does something. Or have you found all markup on IDL blocks to be unnecessary?

**Comment by saschanaz** [comment]
I'm deliberately filtering specs that includes valid markups inside IDL:

https://github.com/saschanaz/webidl-updater/blob/0cf10252a7a31b48537bc098adf1088b2074cf24/src/github-pullrequest.js#L148-L152

Markups in Fullscreen didn't seem to do anything so I didn't include it in this list. If you inspect the result, you can see the types get `<dfn>` automatically even when the bot removed them.

But if they do something, I can modify the incompatibility list.

**Comment by annevk** [comment]
I think @saschanaz might be right that the markup in Fullscreen is leftover from when we used Anolis and can be removed.

**Comment by foolip** [comment]
I'm removing it in https://github.com/whatwg/fullscreen/pull/159, it had no effect at all.
