### ISSUE TITLE
Highly confusing further commits

### ISSUE THREAD

**Issue by gsnedders** [saschanaz/webidl-updater#6]
See, e.g., https://github.com/w3c/csswg-drafts/pull/4387.

While https://github.com/w3c/csswg-drafts/pull/4387/commits/036971a96e8ff0d53c720ae99ab89a563276a1c4 is obvious, https://github.com/w3c/csswg-drafts/pull/4387/commits/ae827bf0ccf3bbaf301d742fb3caa210f239d7fa is much less so.

I presume this is caused by re-running the bot against master when there's a conflict or something, but not actually changing the base of the branch?

**Comment by saschanaz** [comment]
Thank you for reporting this! I tried fixing this in 13cc6ea5dd714c03d5d0bb0cf3af383d832e24bc, please report if same happens again.
