### ISSUE TITLE
autokagami is picking up additional unrelated commits in its PRs?

### ISSUE THREAD

**Issue by tabatkins** [saschanaz/webidl-updater#7]
In <https://github.com/w3c/csswg-drafts/pull/4385>, @autokagami produces a reasonable first commit in its PR last September, but then in November it added another commit to the PR that reproduces the changes of a *completely unrelated* commit to that document.

I presume this is some mistake with handling rebasing onto the latest version of a document?

**Comment by saschanaz** [comment]
Seems it indeed has a problem. Will track this on #6.
